export const MissionEvents = {
  LOGIN: "LOGIN",
  START_MINING: "START_MINING",
  FINISH_MINING: "FINISH_MINING",
  VISIT_GALAXY: "VISIT_GALAXY",
  VISIT_PASSPORT: "VISIT_PASSPORT",
  VERIFY_TELEGRAM: "VERIFY_TELEGRAM",
  VERIFY_X: "VERIFY_X",
  VERIFY_INSTAGRAM: "VERIFY_INSTAGRAM",
  COMPLETE_MISSION: "COMPLETE_MISSION",
  INVITE_BUILDER: "INVITE_BUILDER",
  DISCOVER_OBJECT: "DISCOVER_OBJECT",
  PLAY_MINIGAME: "PLAY_MINIGAME",
  WATCH_ACADEMY: "WATCH_ACADEMY",
  SPIN_DAILY: "SPIN_DAILY",
  CLAIM_REWARD: "CLAIM_REWARD",
} as const;

export type MissionEventType =
  (typeof MissionEvents)[keyof typeof MissionEvents];
