begin;

-- ============================================================
-- BOBU UNIVERSE
-- MARS PIXEL ANALYTICS ENGINE v40
--
-- Public event ingestion:
--   impression
--   card_open
--   cta_click
--
-- Private owner analytics:
--   7 / 30 / 90 day territory statistics
--
-- No payment, allocation, creative or moderation mutation.
-- ============================================================

create table if not exists public.mars_pixel_ad_events (
  id bigint generated by default as identity primary key,

  allocation_id uuid not null
    references public.mars_pixel_allocations(id)
    on delete restrict,

  event_type text not null
    check (
      event_type in (
        'impression',
        'card_open',
        'cta_click'
      )
    ),

  session_key text,
  occurred_at timestamptz not null default now(),

  created_at timestamptz not null default now()
);

create index if not exists
  mars_pixel_ad_events_allocation_time_idx
on public.mars_pixel_ad_events (
  allocation_id,
  occurred_at desc
);

create index if not exists
  mars_pixel_ad_events_type_time_idx
on public.mars_pixel_ad_events (
  event_type,
  occurred_at desc
);

alter table public.mars_pixel_ad_events
  enable row level security;

revoke all
on table public.mars_pixel_ad_events
from public, anon, authenticated;


-- ------------------------------------------------------------
-- PUBLIC EVENT INGESTION
-- ------------------------------------------------------------

create or replace function public.record_mars_pixel_ad_event_v1(
  p_allocation_id uuid,
  p_event_type text,
  p_session_key text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_event_type text;
  v_session_key text;
begin
  if p_allocation_id is null then
    return;
  end if;

  v_event_type := lower(trim(coalesce(p_event_type, '')));

  if v_event_type not in (
    'impression',
    'card_open',
    'cta_click'
  ) then
    raise exception 'MARS_PIXEL_INVALID_ANALYTICS_EVENT'
      using errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.mars_pixel_allocations as allocation
    join public.mars_advertisers as advertiser
      on advertiser.id = allocation.advertiser_id
    join public.mars_ad_creatives as creative
      on creative.allocation_id = allocation.id
    where allocation.id = p_allocation_id
      and allocation.allocation_status = 'owned'
      and advertiser.status = 'active'
      and creative.status = 'active'
  ) then
    return;
  end if;

  v_session_key :=
    nullif(
      left(
        trim(coalesce(p_session_key, '')),
        128
      ),
      ''
    );

  insert into public.mars_pixel_ad_events (
    allocation_id,
    event_type,
    session_key
  )
  values (
    p_allocation_id,
    v_event_type,
    v_session_key
  );
end;
$$;

revoke all
on function public.record_mars_pixel_ad_event_v1(
  uuid,
  text,
  text
)
from public;

grant execute
on function public.record_mars_pixel_ad_event_v1(
  uuid,
  text,
  text
)
to anon, authenticated;


-- ------------------------------------------------------------
-- OWNER-ONLY ANALYTICS
-- ------------------------------------------------------------

create or replace function public.get_my_mars_pixel_ad_analytics_v1(
  p_days integer default 30
)
returns table (
  allocation_id uuid,
  period_days integer,
  impressions bigint,
  card_opens bigint,
  cta_clicks bigint,
  ctr numeric,
  last_event_at timestamptz
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_days integer;
begin
  if v_user_id is null then
    raise exception 'MARS_PIXEL_AUTH_REQUIRED'
      using errcode = '42501';
  end if;

  if p_days not in (7, 30, 90) then
    raise exception 'MARS_PIXEL_INVALID_ANALYTICS_PERIOD'
      using errcode = '22023';
  end if;

  v_days := p_days;

  return query
  select
    allocation.id,
    v_days,

    count(event.id)
      filter (
        where event.event_type = 'impression'
      )::bigint as impressions,

    count(event.id)
      filter (
        where event.event_type = 'card_open'
      )::bigint as card_opens,

    count(event.id)
      filter (
        where event.event_type = 'cta_click'
      )::bigint as cta_clicks,

    case
      when count(event.id)
        filter (
          where event.event_type = 'impression'
        ) > 0
      then round(
        (
          count(event.id)
            filter (
              where event.event_type = 'cta_click'
            )::numeric
          /
          count(event.id)
            filter (
              where event.event_type = 'impression'
            )::numeric
        ) * 100,
        2
      )
      else 0::numeric
    end as ctr,

    max(event.occurred_at) as last_event_at

  from public.mars_pixel_allocations as allocation

  join public.mars_advertisers as advertiser
    on advertiser.id = allocation.advertiser_id

  left join public.mars_pixel_ad_events as event
    on event.allocation_id = allocation.id
   and event.occurred_at >=
     now() - make_interval(days => v_days)

  where advertiser.owner_builder_id = v_user_id
    and allocation.allocation_status = 'owned'

  group by allocation.id

  order by allocation.created_at desc;
end;
$$;

revoke all
on function public.get_my_mars_pixel_ad_analytics_v1(integer)
from public, anon, authenticated;

grant execute
on function public.get_my_mars_pixel_ad_analytics_v1(integer)
to authenticated;

comment on table public.mars_pixel_ad_events is
'Mars Pixel server-recorded advertising interaction events. Direct table access is disabled; events are accepted through controlled RPC only.';

comment on function public.record_mars_pixel_ad_event_v1(
  uuid,
  text,
  text
) is
'Controlled public Mars Pixel analytics event ingestion for active owned advertisements.';

comment on function public.get_my_mars_pixel_ad_analytics_v1(integer) is
'Owner-only Mars Pixel advertising analytics for 7, 30 or 90 day periods.';

commit;
