-- ============================================================
-- BOBU UNIVERSE
-- GP Storage v2
--
-- Adds separate Personal GP and Network GP balances while
-- preserving builder_profiles.gp as the legacy total balance.
-- ============================================================


-- ============================================================
-- BUILDER PROFILE GP BALANCES
-- ============================================================

alter table public.builder_profiles
  add column if not exists personal_gp bigint
  not null default 0
  check (personal_gp >= 0);

alter table public.builder_profiles
  add column if not exists pending_network_gp bigint
  not null default 0
  check (pending_network_gp >= 0);

alter table public.builder_profiles
  add column if not exists eligible_network_gp bigint
  not null default 0
  check (eligible_network_gp >= 0);


comment on column public.builder_profiles.personal_gp is
  'GP earned directly by the Builder through mining, missions, achievements, verification and other personal activity.';

comment on column public.builder_profiles.pending_network_gp is
  'Network GP generated by referral activity that is not yet eligible to count toward the Builder total.';

comment on column public.builder_profiles.eligible_network_gp is
  'Network GP that has satisfied eligibility requirements and counts toward the Builder total GP.';


-- ============================================================
-- BACKFILL EXISTING BUILDERS
--
-- Existing total GP is personal GP because Network GP has not
-- been activated yet.
-- ============================================================

update public.builder_profiles
set
  personal_gp = gp,
  pending_network_gp = 0,
  eligible_network_gp = 0;


-- ============================================================
-- PERFORMANCE INDEXES
-- ============================================================

create index if not exists
  builder_profiles_personal_gp_idx
on public.builder_profiles(personal_gp desc);

create index if not exists
  builder_profiles_eligible_network_gp_idx
on public.builder_profiles(eligible_network_gp desc);

create index if not exists
  builder_profiles_pending_network_gp_idx
on public.builder_profiles(pending_network_gp desc);


-- ============================================================
-- PERSONAL GP AWARD ENGINE
--
-- Existing award_builder_gp() rewards are personal GP.
-- builder_profiles.gp remains:
--
--   personal_gp + eligible_network_gp
--
-- Pending Network GP never counts toward total GP.
-- ============================================================

create or replace function public.award_builder_gp(
  p_builder_id uuid,
  p_reward_type text,
  p_amount bigint,
  p_idempotency_key text,
  p_provider text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  awarded boolean,
  total_gp bigint,
  ledger_id uuid
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_ledger_id uuid;
  v_total_gp bigint;
begin
  if p_builder_id is null then
    raise exception 'Builder ID is required';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception
      'Reward amount must be greater than zero';
  end if;

  if p_reward_type is null
     or char_length(trim(p_reward_type)) = 0 then
    raise exception 'Reward type is required';
  end if;

  if p_idempotency_key is null
     or char_length(trim(p_idempotency_key)) = 0 then
    raise exception 'Idempotency key is required';
  end if;

  if p_metadata is null
     or jsonb_typeof(p_metadata) <> 'object' then
    raise exception
      'Reward metadata must be a JSON object';
  end if;

  insert into public.builder_profiles (
    builder_id
  )
  values (
    p_builder_id
  )
  on conflict (builder_id) do nothing;

  insert into public.builder_reward_ledger (
    builder_id,
    reward_type,
    provider,
    amount,
    idempotency_key,
    metadata
  )
  values (
    p_builder_id,
    trim(p_reward_type),
    nullif(trim(p_provider), ''),
    p_amount,
    trim(p_idempotency_key),
    p_metadata
  )
  on conflict (
    builder_id,
    idempotency_key
  )
  do nothing
  returning id into v_ledger_id;

  if v_ledger_id is null then
    select profile.gp
    into v_total_gp
    from public.builder_profiles as profile
    where profile.builder_id = p_builder_id;

    return query
    select
      false,
      coalesce(v_total_gp, 0),
      null::uuid;

    return;
  end if;

  update public.builder_profiles
  set
    personal_gp =
      personal_gp + p_amount,
    gp =
      personal_gp +
      p_amount +
      eligible_network_gp
  where builder_id = p_builder_id
  returning gp into v_total_gp;

  return query
  select
    true,
    v_total_gp,
    v_ledger_id;
end;
$$;


revoke all
on function public.award_builder_gp(
  uuid,
  text,
  bigint,
  text,
  text,
  jsonb
)
from public, anon, authenticated;

grant execute
on function public.award_builder_gp(
  uuid,
  text,
  bigint,
  text,
  text,
  jsonb
)
to service_role;


-- ============================================================
-- PERSONAL GP REVERSAL ENGINE
--
-- Existing reversals reduce Personal GP only.
-- Network GP reversals will use a dedicated future function.
-- ============================================================

create or replace function public.reverse_builder_gp(
  p_builder_id uuid,
  p_amount bigint,
  p_idempotency_key text,
  p_provider text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns table (
  reversed boolean,
  total_gp bigint,
  ledger_id uuid
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_ledger_id uuid;
  v_total_gp bigint;
begin
  if p_builder_id is null then
    raise exception 'Builder ID is required';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception
      'Reversal amount must be greater than zero';
  end if;

  if p_idempotency_key is null
     or char_length(trim(p_idempotency_key)) = 0 then
    raise exception 'Idempotency key is required';
  end if;

  if p_metadata is null
     or jsonb_typeof(p_metadata) <> 'object' then
    raise exception
      'Reversal metadata must be a JSON object';
  end if;

  insert into public.builder_profiles (
    builder_id
  )
  values (
    p_builder_id
  )
  on conflict (builder_id) do nothing;

  insert into public.builder_reward_ledger (
    builder_id,
    reward_type,
    provider,
    amount,
    entry_type,
    idempotency_key,
    metadata
  )
  values (
    p_builder_id,
    'reward_reversal',
    nullif(trim(p_provider), ''),
    p_amount,
    'debit',
    trim(p_idempotency_key),
    p_metadata
  )
  on conflict (
    builder_id,
    idempotency_key
  )
  do nothing
  returning id into v_ledger_id;

  if v_ledger_id is null then
    select profile.gp
    into v_total_gp
    from public.builder_profiles as profile
    where profile.builder_id = p_builder_id;

    return query
    select
      false,
      coalesce(v_total_gp, 0),
      null::uuid;

    return;
  end if;

  update public.builder_profiles
  set
    personal_gp =
      greatest(
        personal_gp - p_amount,
        0
      ),
    gp =
      greatest(
        personal_gp - p_amount,
        0
      ) +
      eligible_network_gp
  where builder_id = p_builder_id
  returning gp into v_total_gp;

  return query
  select
    true,
    v_total_gp,
    v_ledger_id;
end;
$$;


revoke all
on function public.reverse_builder_gp(
  uuid,
  bigint,
  text,
  text,
  jsonb
)
from public, anon, authenticated;

grant execute
on function public.reverse_builder_gp(
  uuid,
  bigint,
  text,
  text,
  jsonb
)
to service_role;


comment on function public.award_builder_gp(
  uuid,
  text,
  bigint,
  text,
  text,
  jsonb
) is
  'Atomically credits Personal GP, writes an immutable ledger entry and maintains total GP as Personal GP plus eligible Network GP.';

comment on function public.reverse_builder_gp(
  uuid,
  bigint,
  text,
  text,
  jsonb
) is
  'Atomically creates an immutable Personal GP debit entry and maintains total GP as Personal GP plus eligible Network GP.';
