-- ============================================================
-- BOBU UNIVERSE
-- Network GP Promotion Engine
--
-- Promotes Pending Network GP into Eligible Network GP after
-- the complete referral path from the source Builder to the
-- recipient becomes active.
--
-- Eligible Network GP counts toward total GP but remains
-- unavailable for wallet migration until the recipient's own
-- wallet activation requirements are satisfied.
-- ============================================================

begin;


create or replace function
public.promote_pending_network_gp(
  p_builder_id uuid,
  p_source_builder_id uuid
)
returns table (
  promoted boolean,
  promoted_amount bigint,
  promoted_entries bigint,
  pending_network_gp bigint,
  eligible_network_gp bigint,
  total_gp bigint,
  promoted_at timestamptz,
  reason text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_relationship_active boolean := false;

  v_promoted_amount bigint := 0;
  v_promoted_entries bigint := 0;
  v_promoted_at timestamptz := now();

  v_pending_network_gp bigint := 0;
  v_eligible_network_gp bigint := 0;
  v_total_gp bigint := 0;
begin
  if p_builder_id is null then
    raise exception
      'Network GP recipient Builder ID is required';
  end if;

  if p_source_builder_id is null then
    raise exception
      'Network GP source Builder ID is required';
  end if;

  if p_builder_id = p_source_builder_id then
    raise exception
      'A Builder cannot promote Network GP generated by themselves';
  end if;

  /*
   * Every relationship in the ancestry path must be active.
   * The path is limited to ten referral levels.
   */
  with recursive active_ancestry as (
    select
      referral.referrer_id as ancestor_id,
      referral.referred_id as descendant_id,
      1 as depth
    from public.builder_referrals as referral
    where referral.referred_id =
      p_source_builder_id
      and referral.status = 'active'

    union all

    select
      parent.referrer_id as ancestor_id,
      ancestry.ancestor_id as descendant_id,
      ancestry.depth + 1 as depth
    from active_ancestry as ancestry
    join public.builder_referrals as parent
      on parent.referred_id =
        ancestry.ancestor_id
      and parent.status = 'active'
    where ancestry.depth < 10
  )
  select exists (
    select 1
    from active_ancestry as ancestry
    where ancestry.ancestor_id = p_builder_id
  )
  into v_relationship_active;

  if not v_relationship_active then
    select
      profile.pending_network_gp,
      profile.eligible_network_gp,
      profile.gp
    into
      v_pending_network_gp,
      v_eligible_network_gp,
      v_total_gp
    from public.builder_profiles as profile
    where profile.builder_id = p_builder_id;

    return query
    select
      false,
      0::bigint,
      0::bigint,
      coalesce(v_pending_network_gp, 0),
      coalesce(v_eligible_network_gp, 0),
      coalesce(v_total_gp, 0),
      null::timestamptz,
      'active_referral_path_required'::text;

    return;
  end if;

  /*
   * Serialize all balance changes for the recipient.
   */
  select
    profile.pending_network_gp,
    profile.eligible_network_gp,
    profile.gp
  into
    v_pending_network_gp,
    v_eligible_network_gp,
    v_total_gp
  from public.builder_profiles as profile
  where profile.builder_id = p_builder_id
  for update;

  if not found then
    raise exception
      'Network GP recipient Builder profile was not found';
  end if;

  /*
   * Lock and promote the exact same rows in one SQL statement.
   * Only rows returned by promoted_rows contribute to the
   * balance movement.
   */
  with locked_pending_entries as (
    select ledger.id
    from public.builder_network_gp_ledger as ledger
    where ledger.builder_id = p_builder_id
      and ledger.source_builder_id =
        p_source_builder_id
      and ledger.status = 'pending'
    order by
      ledger.created_at asc,
      ledger.id asc
    for update
  ),
  promoted_rows as (
    update public.builder_network_gp_ledger as ledger
    set
      status = 'eligible',
      promoted_at = coalesce(
        ledger.promoted_at,
        v_promoted_at
      )
    from locked_pending_entries as locked
    where ledger.id = locked.id
      and ledger.status = 'pending'
    returning ledger.amount
  )
  select
    coalesce(sum(promoted.amount), 0)::bigint,
    count(*)::bigint
  into
    v_promoted_amount,
    v_promoted_entries
  from promoted_rows as promoted;

  if v_promoted_entries = 0 then
    return query
    select
      false,
      0::bigint,
      0::bigint,
      v_pending_network_gp,
      v_eligible_network_gp,
      v_total_gp,
      null::timestamptz,
      'no_pending_network_gp'::text;

    return;
  end if;

  if v_promoted_amount <= 0 then
    raise exception
      'Pending Network GP promotion amount must be greater than zero';
  end if;

  if v_pending_network_gp < v_promoted_amount then
    raise exception
      'Pending Network GP balance is lower than the promotion amount';
  end if;

  update public.builder_profiles as profile
  set
    pending_network_gp =
      profile.pending_network_gp -
      v_promoted_amount,

    eligible_network_gp =
      profile.eligible_network_gp +
      v_promoted_amount,

    gp =
      profile.personal_gp +
      profile.eligible_network_gp +
      v_promoted_amount

  where profile.builder_id = p_builder_id

  returning
    profile.pending_network_gp,
    profile.eligible_network_gp,
    profile.gp
  into
    v_pending_network_gp,
    v_eligible_network_gp,
    v_total_gp;

  return query
  select
    true,
    v_promoted_amount,
    v_promoted_entries,
    v_pending_network_gp,
    v_eligible_network_gp,
    v_total_gp,
    v_promoted_at,
    'promoted'::text;
end;
$$;


revoke all
on function public.promote_pending_network_gp(
  uuid,
  uuid
)
from public, anon, authenticated;

grant execute
on function public.promote_pending_network_gp(
  uuid,
  uuid
)
to service_role;


comment on function
public.promote_pending_network_gp(
  uuid,
  uuid
) is
  'Atomically promotes the exact locked Pending Network GP entries generated by one source Builder for one eligible ancestor and recalculates total GP.';


commit;
